proposal.md
=> Web Project Proposal

docker-compose-fullbuild.yml, docker-compose.yml, frontend/.eslintrc.js
Need to include eslintrc and custom lint rules to the volume to be able to resolve import lint issue with all files in src as well gatsby specific files outside the src directory
=> Fix issue with linting and docker

.github/workflows/publish-dev.yml, .github/workflows/publish-docs.yml, cms/.gitignore, cms/robots.txt
Only setting up dev server pipeline for now. Will set up the pipeline for a mock real site later.
=> [9] Set up deployment pipeline to dev server

frontend/src/pages/index.js
Put back removed code from main page
=> Put back main page code

frontend/src/components/page-new/gotQuestions.js, frontend/src/components/svgs/index.js, frontend/src/config/theme.js, frontend/src/pages/new/index.js
=> 51-Got-Questions-New-Page

frontend/src/components/page-about/index/values.js, frontend/src/css/values.module.css, frontend/src/pages/about/index.js, frontend/src/pages/about/partners.js, package.json
Values component for about section. 
- Not desktop responsive, at screen width 1175px 100% zoom view text wraps around and is misaligned. 
- Also not mobile responsive, but Dominic mentioned he would take care of it. 
- Shares CSS modules with belief CSS module and includes its own for formatting SaLT CoMManD and also requiring a specific ordering the Collapsible components.
=> 52 - About section our values

cms/package.json
Security incident: https://github.com/hmcc-global/hmccaa-web/security/dependabot/10
=> upgrade strapi to 4.10.8

frontend/src/components/page-watch/rightNowMedia.js, frontend/src/components/svgs/index.js, frontend/src/css/button.module.css, frontend/src/css/global.css, frontend/src/css/rightNowMedia.module.css, frontend/src/pages/watch/index.js
=> [43] RightNow Media on  Watch Page

frontend/.gitignore, frontend/public/.htaccess
Add .htaccess to link all 404s to /404 page
=> Add .htaccess for 404 page

frontend/src/components/page-main/upcoming.js, frontend/src/components/page-main/welcomeMain.js, frontend/src/components/shared/highlightedParagraph.module.css
=> Updated Home Page for Mobile

frontend/src/components/page-new/sunday-celebration.js, frontend/src/components/page-new/sunday-celebration.module.css, frontend/src/components/page-new/welcome.js, frontend/src/components/page-watch/liveStream.js, frontend/src/components/page-watch/rightNowMedia.js, frontend/src/config/theme.js, frontend/src/css/media.module.css, frontend/src/css/rightNowMedia.module.css, frontend/src/pages/new/index.js, frontend/src/pages/watch/index.js
Currently have a placeholder for video, image, or what ever asset we want to place in this section
=> [41] Adding Live Stream Section

.github/workflows/publish-dev.yml, .github/workflows/publish-docs.yml, .github/workflows/publish-prod.yml
Merges dev pipelines into one and temporarily deprecates prod pipeline
=> [91|92|93] Pipeline refactor

frontend/src/components/header.js
=> [84] hamburger scrolling

frontend/src/components/page-give/why-we-give-section.js, frontend/src/components/page-new/lifeStages.js, frontend/src/components/page-next-steps/ministryTeams.js, frontend/src/components/page-watch/liveStream.js, frontend/src/pages/connect/index.js, frontend/src/pages/connect/life-stages.js, frontend/src/pages/next-steps/index.js
* Fix apostrophe on giving page
* Fix text align in life stages section of I'm New page
* Fix capitalization and typos in Ministry Teams section of Next Steps page
* Fix missing commas on Watch page
* Remove scaffolding divs on Connect page
* Add missing italicization in Life Stages section of Connect page
* Remove scaffolding divs from next steps page
=> Miscellaneous text and spacing fixes

frontend/src/components/footer.js
Fixes https://github.com/hmcc-global/hmccaa-web/issues/102
Before:
After:
=> [88] Fix padding in footer for mobile view

docs/index.md, frontend/src/components/Button.js, frontend/src/components/Link.js, frontend/src/components/footer.js, frontend/src/components/header.js, frontend/src/components/instaBar.js, frontend/src/components/page-events/event-processing-util.js, frontend/src/components/page-events/prayerGatheringEvents.js, frontend/src/components/page-new/lifeStages.js, frontend/src/components/page-next-steps/ministryTeams.js, frontend/src/components/page-watch/rightNowMedia.js, frontend/src/pages/connect/life-stages.js, frontend/src/pages/events/index.js
=> Added link documentation

frontend/src/components/header.js, frontend/src/config/theme.js, frontend/src/css/global.css, frontend/src/pages/events/index.js
=> Update Mobile Drop Down Menu

frontend/src/components/header.js, package.json
bunch of files also changed due to linter
new
old
=> Fix location dropdown on navbar

frontend/src/components/page-about/index/feedback.js
previously empty link now filled
=> fix feedback form link #127

frontend/src/components/page-about/index/our-story.js, frontend/src/components/page-main/getconnected.js, frontend/src/components/page-new/lifeStages.js, frontend/src/components/page-next-steps/ministryTeams.js, frontend/src/components/page-next-steps/missionsNextSteps.js, frontend/src/pages/index.js
=> Fixed text #197 #198

frontend/src/components/header.js, frontend/src/components/instaBar.js, frontend/src/components/layout.css, frontend/src/components/page-about/index/belief.js, frontend/src/components/page-about/index/leadership.js, frontend/src/components/page-about/index/values.js, frontend/src/components/page-watch/index/sermonCard.js, frontend/src/components/shared/card.js, frontend/src/components/shared/comboBox.js, frontend/src/css/belief.module.css
https://github.com/hmcc-global/hmccaa-web/issues/125 :
https://github.com/hmcc-global/hmccaa-web/issues/164 :
https://github.com/hmcc-global/hmccaa-web/issues/169 : 
https://github.com/hmcc-global/hmccaa-web/issues/133 :
=> Updates for Issues

frontend/src/components/page-events/prayerGatheringEvents.js
=> [176] - Widen text for Bible verse on Prayer Gathering section of Event page

frontend/src/components/footer.js
=> Remove interest form from footer + Update Year in Footer to Be Dynamic

frontend/src/components/page-about/index/values.js, frontend/src/css/values.module.css
=> Update salt command visual fix #199

frontend/src/pages/404.js
If I understood issue #182 correctly, I changed the Google Form URL to `/next-steps/lifegroups` aka the lifegroup page.
=> Changed LG signup link to /next-steps/lifegroups

frontend/src/components/page-next-steps/missionsNextSteps.js
is now centered on smaller screen sizes. look at issue #216 for before
=> fix missions learn more button not centered #216

frontend/src/components/page-main/getinvolved.js, frontend/src/components/page-new/lifeStages.js, frontend/src/components/page-new/welcome.js
also fixed wording. questionnaire now also opens in new tab.
=> fix #223 & #225

frontend/src/components/page-events/eventsNote.js, frontend/src/pages/events/index.js, frontend/src/pages/next-steps/baptism.js, frontend/src/pages/next-steps/membership.js, frontend/src/pages/next-steps/transformation.js
links described in #222 are fixed and now point to events page. additional line also added in events page about those classes
=> Fix broken links #222

frontend/src/pages/index.js
=> Update home text positioning fix #233

docs/src/setup.md
Addressing Issue #212 
Add references to cms/.env; frontend/.env.development
Add debugging tips for errors in launching the frontend and reorganized sections
=> Setup Doc Improvement

frontend/src/components/page-lifeGroups/life.js
=> Life Group format fixes

frontend/src/components/svgs/index.js
=> Icon updates fix #232

frontend/src/components/page-events/eventsNote.js, frontend/src/components/shared/card.js, frontend/src/pages/events/index.js
=> 129 event card mobile

frontend/src/pages/about/hmi.js
=> HMI update text & fix typos

frontend/src/components/page-about/index/our-story.js, frontend/src/components/page-about/index/partners.js, frontend/src/components/page-about/index/values.js
=> [About] Text updates

frontend/src/components/page-about/index/values.js
=> remove gaps in column form

frontend/gatsby-config.js, frontend/src/components/footer.js, frontend/src/components/page-about/index/strategy.js, frontend/src/components/page-about/team/eldersSection.js, frontend/src/components/page-lifeGroups/fiveEs.js, frontend/src/components/page-lifeGroups/topLGSummary.js, frontend/src/components/page-main/getconnected.js, frontend/src/components/page-main/welcomeMain.js, frontend/src/components/page-next-steps/lifeGroup.js, frontend/src/pages/connect/life-stages.js, frontend/src/pages/next-steps/lifegroups.js
only updated within sentences. titles, buttons, links, and wherever else was not updated.
=> Updated LIFE Group references to address #255

frontend/src/pages/about/hmi.js
Click through more info links to verify
fixes #276
=> [276] More Info button links

frontend/src/components/page-about/shared/teamCard.js, frontend/src/components/page-about/team/deaconsSection.js, frontend/src/components/page-about/team/eldersSection.js
danny and phi also reordered to match figma
=> Fix #273 about page wording

frontend/src/components/Link.js, frontend/src/components/page-lifeGroups/fiveEs.js, frontend/src/components/page-lifeGroups/topLGSummary.js, frontend/src/pages/next-steps/lifegroups.js
mobile
scrolling and new links
https://github.com/hmcc-global/hmccaa-web/assets/88253868/31c10432-5f24-4487-bece-f90e61906ca1
=> Update lifegroup signups fix #263

frontend/src/components/page-watch/index/sermons.js
=> [Sermons] - Change color of active/inactive pages

frontend/src/components/page-events/event-processing-util.js, frontend/src/components/page-events/event-processing.js, frontend/src/pages/events/index.js
Fixes bugs:
- event times were sorted per event template and not for all events
- frontend page doesn't auto update when event has passed, would require a rebuild
=> fix events sorting and display logic

frontend/src/components/header.js
=> Redesign I'm New button & Allow whole row to be clickable

frontend/src/components/header.js
fixes #331 
Apply active state to Link so that color fills on a finger down event
Fix design so the background fill is only applied if the I'm new page is active
While on /new/
=> [I'm New] Design fix

frontend/src/components/page-about/team/heading.js
=> Our team text centered, max width applied

frontend/src/components/header.js
=> Add Home tab to mobile nav menu

frontend/src/components/header.js
=> Hide home link on desktop view

frontend/gatsby-node.js
Reverts hmcc-global/hmccaa-web#414
=> Revert "add redirect from /lg to life groups page"

frontend/src/pages/about/hmi.js
=> Fix alignment issue for the missionaries grid

frontend/gatsby-node.js, frontend/src/components/page-events/event-processing-util.js, frontend/src/components/page-watch/index/sermons.js, frontend/src/components/shared/card.js, frontend/src/pages/events/index.js, frontend/src/templates/eventPageTemplate.js
- Shows end times if it's specified
- If time is 00:00, then it is not shown
- If time is 00:00 and there is also an end datetime specified, then:
- If end time is also 00:00, neither is specified
- If end time is NOT 00:00, then both times are specified
=> Fix event times

frontend/src/pages/index.js
Fixes broken link to page that doesn't exist anymore
=> Hotfix 2024-10-30

frontend/src/components/page-about/team/deaconsSection.js, frontend/src/components/page-about/team/eldersSection.js
=> Updates for center team page

frontend/gatsby-config.js, frontend/src/components/page-events/event-processing-util.js, frontend/src/pages/get-involved/missions.js
=> missions frontend

frontend/src/components/page-new/common-questions.js, frontend/src/components/page-new/map-details.js
=> Redesign map details & common questions spacing/alignment

frontend/src/components/shared/richText.js
=> Give RichText a collapsible option

frontend/src/components/shared/banner.js, frontend/src/components/shared/richText.js, frontend/src/templates/customPage.js
or defaults to this if one is not provided:
=> Custom page now supports background images

frontend/src/components/collapsible.js, frontend/src/components/layout.js, frontend/src/css/global.css, frontend/src/pages/index.js, frontend/src/templates/customPage.js
=> Updates UX for custom Page for Collapisble 

frontend/src/css/global.css
=> Fix Notification Bar Issue 

frontend/src/css/global.css
Hotfix for:
- updates to notification bar (#504)
=> Hotfix 20250112

frontend/gatsby-config.js, frontend/src/components/page-main/getconnected.js, frontend/src/pages/404.js, frontend/src/pages/new/life-stages.js
* Fix links that were still going to connect page
* more fixes to point to life-stages page
* remove dead access website button
=> Fix links that were still going to connect page (#510)

frontend/src/components/page-lifeGroups/topLGSummary.js, frontend/src/components/page-watch/rightNowMedia.js, frontend/src/pages/get-involved/lifegroups.js
=> Add LG Video

frontend/gatsby-config.js, frontend/src/components/shared/notificationBar.js, frontend/src/components/shared/richText.js, frontend/src/pages/about/hmi.js, frontend/src/pages/get-involved/missions.js
Use strapi to load supported missionaries
=> Use strapi to load supported missionaries

cms/src/api/supported-missionary/content-types/supported-missionary/schema.json, cms/src/api/supported-missionary/controllers/supported-missionary.js, cms/src/api/supported-missionary/routes/supported-missionary.js, cms/src/api/supported-missionary/services/supported-missionary.js, frontend/gatsby-config.js, frontend/src/components/page-lifeGroups/topLGSummary.js, frontend/src/components/page-watch/rightNowMedia.js, frontend/src/components/shared/notificationBar.js, frontend/src/components/shared/richText.js, frontend/src/pages/about/hmi.js, frontend/src/pages/get-involved/lifegroups.js, frontend/src/pages/get-involved/missions.js
- Adds LG video to LG page
- Adds supported missionary strapi support
=> Release 2025-03-01

frontend/src/components/page-lifeGroups/fiveEs.js, frontend/src/components/page-watch/index/sermons.js
=> 2025-03-30 Hotfix

frontend/src/components/collapsible.js
=> [Mobile] Text padding for I'm new text sections

frontend/src/components/shared/richText.js
=> Add break-all class to text formatting for improved text wrapping

frontend/src/components/page-lifeGroups/fiveEs.js, frontend/src/components/svgs/index.js
=> Updates to better Center E

frontend/src/components/page-watch/liveStream.js
=> Live Stream Fix for center component

frontend/src/components/shared/richText.js
=> Fix word break in Rich Text
