hmcc-global/hmccaa-web

cms/Dockerfile
cms/package-lock.json
cms/package.json
docker-compose-fullbuild.yml
docker-compose.yml
frontend/Dockerfile
frontend/Dockerfile-FullBuildFrontend
frontend/gatsby-config.js
frontend/package-lock.json
frontend/package.json
frontend/scripts/wait-for-strapi.sh
frontend/src/components/page-watch/index/sermons.js
frontend/src/pages/watch/index.js

- Sets up strapi/gatsby to connect to one another on Docker (previously they were running concurrently but separately)
- built new docker images for amd64 (v0.1.3)
- Script to make gatsby wait for strapi to be up before trying to build
- Because Gatsby now relies on Strapi to build, we can no longer store the pre-built version on the docker image. v0.1.3 reflects this - so cached builds will take longer.
- Perhaps worth considering simplifying the volumes in docker-compose to just be the base `frontend` folders, including everything?
- Demo of connection and how gatsby pulls info from strapi in the watch/sermons.js file
Next: Documentation for how to use/develop on this

Maplexu/56.1 Set up watch page to connect to backend

---

frontend/src/components/page-about/shared/teamCard.js
frontend/src/css/global.css

fixed the issue with mobile modals sticking just to the top. theres a small margin around the small mobile views now
mobile view of smaller height modal
mobile view of large height modal
medium desktop view unaffected
largest views unaffected

[73] - Mobile Modals update

---

frontend/src/css/global.css

firefox
safari
chrome - has default dark gray pull to refresh for dark mode iphone, not sure how to change this one but to be honest i think it looks fine

[85] Top Bar Above Nav White Issue Fix

---

frontend/src/components/footer.js
frontend/src/components/instaBar.js
frontend/src/components/page-connect/map-details.js
frontend/src/pages/connect/index.js

on the connect page. event page has an ig bar too but its already full width. tested on different screen sizes
ways to connect, updated to point to next steps. although i dont know where the interest form is so its blank for now
url pointed to maps.app which loaded a bit slower than the url in the footer link. changed it to be more consistent

[86] Instagram bar not full width + footer links fix + update map url

---

frontend/src/components/Button.js
frontend/src/components/Link.js
frontend/src/components/footer.js
frontend/src/components/header.js
frontend/src/components/page-about/index/feedback.js
frontend/src/components/page-about/shared/teamCard.js
frontend/src/components/page-connect/map-details.js
frontend/src/components/page-give/how-to-give.js
frontend/src/components/page-lifeGroups/fiveEs.js
frontend/src/components/page-lifeGroups/topLGSummary.js
frontend/src/components/page-new/lifeStages.js
frontend/src/components/page-next-steps/ministryTeams.js
frontend/src/components/page-watch/liveStream.js
frontend/src/components/page-watch/rightNowMedia.js
frontend/src/pages/404.js
frontend/src/pages/connect/life-stages.js
frontend/src/pages/page-2.js

**updated all links including gatsby links, anchors, buttonlinks (primary and secondary)**
links now all look like 
`<Link href="some external site" prop1=x prop2=y>Click here</Link>` 
or
`<Link to="some internal page" prop1=x prop2=y>Click here</Link>` 
href **must** be defined for an external link
to **must** be defined for internal page, otherwise it redirects to home page
any props can be passed down all the way to the original `<a>` or `<GatsbyLink>` element defined in components/Link.js
children can also be rendered in `Link`
i tested every link after making this change. every link that is currently working still works. #127 and #131 are some currently broken links.

[90] link refactor - terrianx/link refactor

---

frontend/src/components/page-events/event-processing-util.js
frontend/src/pages/events/index.js

Fetch events from CMS, and add filtering according to rules.
Test cases verified:
* Empty event with no event template doesn't break the site
* Empty event with a single time
* Event completely using template
* Event with overrides
* Recurring event every day
* Recurring event every 4 days
* Recurring event every 2 weeks
* Recurring event every 2 months
* Recurring event every year
* End Recur date
* Recurring and single event together with showing X future events
* StopShowingWhenPast for single event
* ShowXUpcomingEvents defaults to 1 if no event template
* Events today keep showing until the end of the day

[71] Events page business logic

---

frontend/src/components/header.js
frontend/src/components/page-events/prayerGatheringEvents.js

previously this was happening
now text does not wrap

Fix #93 text wrapping on navigation bar

---

frontend/src/components/header.js
frontend/src/components/shared/banner.js

safari navbar was making the logo super wide before this change. issue was due to min-width not being supported. it was removed and it works now. try to open safari either on phone or desktop and resize the screen down to mobile view.
before
this pr
also improved overall look of different window sizes. previously there was a lot of extra space on either side at a specific width. it is now removed.
before
this pr

Fix safari navbar logo issue and #136 horizontal scroll bar on pages

---

frontend/src/components/page-watch/rightNowMedia.js

look at bottom left tooltip, shows proper link

Fix rightnow media link issue #131

---

frontend/src/css/button.module.css

buttons now change text to orange on hover. no buttons without borders are used

Button hover color change fix #145

---

frontend/src/components/header.js

tested on safari too and it works
smallest screen size that people will be using, most devices have a larger width

Centered text on mobile nav fix issue #186

---

frontend/src/components/page-about/index/leadership.js
frontend/src/css/belief.module.css
frontend/src/css/strategy.module.css

standardized spacing between components in about page
on mobile 80px padding between the sections listed under issue #82
on desktop 160px padding between same sections

fix #82 Spacing on web view on about page is off

---

frontend/src/components/gotQuestions.js

changes into rows on larger screen than before to prevent multiple lines as described in 224

Fix got questions multi line break #224

---

frontend/src/components/page-connect/map-details.js

issue #213 was already addressed in a previous commit but the issue was never closed. normans pr #248 can be closed.
in this pr i made the breakpoint happen sooner since parts of the map was being covered up when resizing the screen.
before
after

Fix map being covered in smaller screens fix #213

---

frontend/src/components/gotQuestions.js
frontend/src/components/layout.js
frontend/src/components/page-about/index/leadership.js
frontend/src/components/page-events/prayerGatheringEvents.js
frontend/src/components/page-main/getconnected.js
frontend/src/components/page-main/getinvolved.js
frontend/src/pages/about/index.js
frontend/src/pages/connect/index.js
frontend/src/pages/events/index.js

layout template component adds two default parameters for whether or not spacing is needed and the color
default with white background, most pages look have this
some backgrounds have a different color like this feedback form section
spacing between got questions and ig bar is 160px
some pages like the baptism one have larger than 160px padding
top of section previously was too far down
header text is now 20px from the body text
increased spacing from next section to be roughly 160px

Fix #278 Vertical spacing on last section of all pages + fix major spacing bugs 

---

frontend/src/components/page-new/sunday-celebration.js

only mobile view is affected by this change.
old: 
new:
desktop view should have no change

fix sunday celebration alignment/padding in im new page

---

docker-compose.yml

Some files in gatsby cache are limited to root access, and this messes with husky's ability to format/check files. Because of currently existing prettierignore bugs, this cannot be fixed by adding the right directories to .prettierignore. Thus, this change will allow husky to freely edit files without being bothered by files in the cache (as long as `git push` is called from outside the docker container... which it should be, considering the container doesn't have git installed...)

Move gatsby cache to docker volume

---

frontend/src/components/footer.js

Top padding for logo on mobile. Split address into 2 lines

---

frontend/gatsby-config.js
frontend/gatsby-node.js
frontend/src/components/shared/notificationBar.js
frontend/src/components/shared/richText.js
frontend/src/css/global.css
frontend/src/page-generation/custom.js
frontend/src/pages/index.js
frontend/src/templates/customPage.js

Desktop view looks the same:
but unfortunately mobile view looks jank. couldn't figure out how to fix it (aka bring the "sign up now" down to the new line without specially hardcoding it
Also created a custom page:
(you can use build this exact custom page yourself if you copy the data from production strapi, I put a copy there as well.

add notification bar and custom page frontend

---

cms/ecosystem.config.js

I think the previous limit (default was 10) was getting hit and causing connections to get dropped and certain graphql requests to fail

Increase Strapi database connection pool limits

---

frontend/src/components/page-watch/index/sermons.js

Address layout inconsistencies in the sermons component and enhance the display of trait labels by replacing underscores with spaces. Also added gap to the y axis to space out cards

Fix layout inconsistencies and improve trait label display
